# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='title',
            new_name='product_title',
        ),
    ]
