# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20191108_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user_feedback',
            field=models.TextField(null=True),
        ),
    ]
