# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20191108_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='views',
        ),
    ]
