# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product_title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='views',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=800),
        ),
    ]
