# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-27 11:09
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191026_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_new',
            name='Score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='feedback_new',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 27, 11, 9, 54, 818250, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
