# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191027_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
