# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-28 14:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback_new',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
