# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-28 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_post_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_favorite',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
