# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feedback',
            field=models.TextField(max_length=30),
        ),
    ]
