# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createdby',
            field=models.CharField(default='username', max_length=20),
        ),
    ]
