# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-05 11:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_post_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='createdby',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
