# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'Large'), ('xl-large', 'XL-LARGE'), ('xx-large', 'XXL-Large')], default='small', max_length=6),
        ),
    ]
