# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('green', 'GREEN'), ('medium', 'YELLOW'), ('large', 'BLUE')], default='blue', max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE'), ('xl-large', 'XL-LARGE'), ('xx-large', 'XXL-LARGE')], default='small', max_length=6),
        ),
    ]
