# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191030_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
